let entrada = [
    {nome: 'Canapés de Ricota com Azeitona', img: 'img/canapes.jpg', alt: 'Foto de Kseniia Lopyreva: https://www.pexels.com/pt-br/foto/aperitivo-lanche-petisco-apetitoso-4959888/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 15.00}, 
    {nome: 'Brusqueta de Cogumelo Paris', img: 'img/brusqueta.jpg', alt: 'Foto de Maria Orlova: https://www.pexels.com/pt-br/foto/salada-de-legumes-em-prato-de-ceramica-branca-4969892/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 13.50},
    {nome: 'Coquetel de Camarão', img: 'img/coquetel-camarao.jpg', alt: '', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 16.00},
    {nome: 'Caprese no Palito', img: 'img/caprese.jpg', alt: '', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 14.00}
]

let principal = [
    {nome: 'Paella', img: 'img/paella.jpg', alt: 'Foto de Le Creuset: https://www.lecreuset.com.br/paella', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 35.00},
    {nome: 'Lagosta ao Thermidor', img: 'img/lagosta.jpg', alt: 'Foto de Rachel Claire: https://www.pexels.com/pt-br/foto/abundancia-fartura-riqueza-aperitivo-5490142/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 50.00},
    {nome: 'Feijoada', img: 'img/feijoada.jpg', alt: 'Foto de Saborosos: https://www.saborosos.com.br/receita/feijoada', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 30.00},
    {nome: 'Lámen', img: 'img/lamen.jpg', alt: 'Foto de DeliRec: https://delirec.com/recipe/wilsonfnunes/lamen-com-copa-lombo/6wPteSEQJkxCGqfmTO0n', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 28.00}
]

let sobremesa = [
    {nome: 'Pudim', img: 'img/pudim.jpg', alt: 'Foto de Stok Center: https://stokcenter.com.br/pudim/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 20.00},
    {nome: 'Sorvete', img: 'img/sorvete.jpg', alt: 'Foto de Valeria Boltneva: https://www.pexels.com/pt-br/foto/apetitoso-tentador-sortido-variado-1683546/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 15.00},
    {nome: 'Cheesecake', img: 'img/cheesecake.jpg', alt: 'Foto de alleksana: https://www.pexels.com/pt-br/foto/cozimento-fornada-assando-baga-4051737/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 12.00},
    {nome: 'Panqueca', img: 'img/panqueca.jpg', alt: 'Foto de Mike Esparza: https://www.pexels.com/pt-br/foto/foto-de-close-up-de-panquecas-3702403/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 10.00}
]

let bebida = [
    {nome: 'Suco', img: 'img/suco.jpg', alt: 'Foto de Conquiste sua Vida: https://www.conquistesuavida.com.br/noticia/7-receitas-de-sucos-refrescantes-e-naturais-para-o-verao_a11497/1', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 8.50},
    {nome: 'Refrigerante', img: 'img/refri.jpg', alt: 'Foto de Ron Lach : https://www.pexels.com/pt-br/foto/bebida-gelada-bebida-drink-copo-de-bebida-8880742/', descricao: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat dolores consequatur odit nulla cum soluta ratione nam nisi hic. Quisquam vel nostrum tempora recusandae magni corporis eligendi et, eos excepturi.', preco: 10.00}
]